# ワークフロー名
name: news-bot

# 発火タイミング
on:
  schedule:
    - cron: '19 9 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install beautifulsoup4
          pip install line-bot-sdk
      - name: Run script
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN}}
          CHANNEL_SECRET: ${{ secrets.CHANNEL_SECRET}}
          USER_ID: ${{ secrets.USER_ID}}
        run: |
          # main.pyの実行
          python main.py
